### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by xiucz** [tobiasrausch/variant-calling#1]
Hi, @tobiasrausch 
Thank you for your work and I have some questions about this SV pipline:
```
coral call
```
1.  Where can I find this software **coral** ?

```
cnBafSV.R
```

2. Where can I find this code?

Thank you very much.
Xiucz.

**Comment by tobiasrausch** [comment]
coral is available in my github repositories:

[https://github.com/tobiasrausch/coral](https://github.com/tobiasrausch/coral)

The script just plots the copy-number estimations from the coral output. I only have this in the course images.
